/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRINT_H_RPCGEN
#define _PRINT_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define PRINT 99
#define PRINTVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define rpc_print 0
extern  enum clnt_stat rpc_print_1(char *, int *, CLIENT *);
extern  bool_t rpc_print_1_svc(char *, int *, struct svc_req *);
extern int print_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define rpc_print 0
extern  enum clnt_stat rpc_print_1();
extern  bool_t rpc_print_1_svc();
extern int print_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRINT_H_RPCGEN */
