/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "print.h"
 /**
  * Servicio que se encarga de imprimir el string que recibe por argumento
 */
bool_t
rpc_print_1_svc(char* impresion, int* result, struct svc_req* rqstp) {

	bool_t retval;
	int ret = printf("%s\n", impresion);
	if (ret == -1) *result = -1;
	else *result = 0;

	return 1;
}

int
print_1_freeresult(SVCXPRT* transp, xdrproc_t xdr_result, caddr_t result) {
	xdr_free(xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
